### ISSUE TITLE
Can't pull the container images

### ISSUE THREAD

**Issue by dhenneke** [element-hq/ess-starter-edition-core#1]
**Describe the bug**
I tried to install the operator but the pods won't start in my cluster:

```
Failed to pull image "docker.io/vectorim/ess-starter-edition-core-operator:2.11.9": rpc error: code = Unknown desc = reading manifest 2.11.9 in docker.io/vectorim/ess-starter-edition-core-operator: requested access to the resource is denied
```

**To Reproduce**
1. Follow the installation steps in the Readme.

**Expected behavior**
The Operator is started in the Kubernetes cluster.

**Comment by gaelgatelement** [comment]
Thanks for reporting the issue, we indeed forgot to make the repository public.

It should be fixed now.
