### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by gigazine-dev** [element-hq/ess-starter-edition-core#3]
**Describe the bug**
I tried to install element-installer-starter-edition-23.09.05-gui.bin by following this: [Single Node Installations | Element Knowledge](https://ems-docs.element.io/books/element-on-premise-documentation/page/single-node-installations)
Then I got this error:

```
TASK [element_operator : Ensure docker secret exists] **************************

task path: /home/foo/.element-enterprise-server/installer/ansible/roles/element_operator/tasks/helm.yml:13

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to apply object: 'NoneType' object is not callable"}


PLAY RECAP *********************************************************************

localhost                  : ok=41   changed=2    unreachable=0    failed=1    skipped=19   rescued=0    ignored=0   
```

**To Reproduce**
1. Follow the installation guide, I only put in email address and changed MAU to 100
2. At The Installation Screen step, I logged out and backed in again
3. Click Install button again

**Versions:**
 - OS: Ubuntu 20.04
 - CPU: Intel Broadwell x86/64

**Comment by gaelgatelement** [comment]
Hello,

Thanks for the report. The issue has been found and we are going to fix it in next release.

**Comment by gaelgatelement** [comment]
It should be fixed in latest release.
