### ISSUE TITLE
Provide images for arm64

### ISSUE THREAD

**Issue by dhenneke** [element-hq/ess-starter-edition-core#4]
**Is your feature request related to a problem? Please describe.**
All big hyperscalers provide cost-effective arm64 based kubernetes worker nodes. It would be nice if the operator could be used in such an infrastructure. Both Element Web and Synapse provide an image for this architecture.

**Describe the solution you'd like**
Provide mutli-arch images that are created for `linux/arm64`.

**Describe alternatives you've considered**
—

**Additional context**
—

**Comment by gaelgatelement** [comment]
Thanks for reporting. It is now fixed in 2.10.11.

**Comment by dhenneke** [comment]
Thanks. The operator starts now 🎉
