### ISSUE TITLE
Possibility of podman or just docker image for the same.

### ISSUE THREAD

**Issue by compgeniuses** [element-hq/ess-starter-edition-core#9]
**Is your feature request related to a problem? Please describe.**
there are many tools available for the deployment and management of docker and podman images, which are easy for entry level users to work with, and play around with. While helm charts is one option for robustly deploying and managing the said prodcut, it could be cumbersome and abit hectic for this deployment, for some cases

this is putting into considerations that the only supported numbe rof users on this is 200 users, An average number for SME actually.

**Describe the solution you'd like**
the solution iw as proposing would be a simplified, docker compose, or even podman files, for making it easy to deploy managae and maintain this for the smallest of SME, this will enable them to use prodcuts such as coolify, nethserver8 others to acheive this robust installation, being feature rich but also devoid of other complexities

**Describe alternatives you've considered**
I am currently building Modules for Nethserver 8 https://www.nethserver.org/nethserver-8/
And since it is geared towars SME and SMB, i was wondering what would be the most feature complete, simples deployment for SME we could have of matrix, and this came to mind. However trying to implement the same is proving cumbersome.

here is a NS8 kickstart module dev, if you consider helping building a module for the same on NS8 https://github.com/NethServer/ns8-kickstart

Another scenario, would be a one touch deployment using coolify.io for the same, however coolify supports docker compose and docker files.

**Additional context**
the Aim of this implementation in my understanding is to get matrix to as many SME as possible, while removing the complexisities of deplying and managing the platform.

these are ways i was wondering if could be considered towards the sam

**Comment by benbz** [comment]
Hi. The focus of this repository is on Helm charts. We may / may not provide other deployment mechanisms in the future, but they'd likely be provided in another repo
